import './globals.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import { Antonio, League_Spartan } from 'next/font/google'

config.autoAddCss = false

import Header from './components/Header'

const spartan = League_Spartan({
  subsets: ['latin'],
  weight: ['500', '700', '400'],
  variable: '--font-spartan',
})

const antonio = Antonio({
  subsets: ['latin'],
  weight: ['500', '700', '400'],
  variable: '--font-antonio',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${antonio.variable} ${spartan.variable}`}>
        <main className="bg-dark text-white min-h-screen w-screen">
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
